tasks:
  1: 
    - name: calc
      queue: calc_queue

  2: 
    - name: trans
      queue: trans_queue

  3:
    - name: encrypt
      queue: encrypt_queue

  4:
    - name: trans
      queue: trans_queue
    - name: encrypt
      queue: encrypt_queue

  5:
    - name: calc
      queue: calc_queue
    - name: encrypt
      queue: encrypt_queue

  6:
    - name: calc
      queue: calc_queue
    - name: trans
      queue: trans_queue
    - name: encrypt
      queue: encrypt_queue  