tasks:
  1: 
    - name: 계산
      queue: calc_queue

  2: 
    - name: 번역
      queue: trans_queue

  3:
    - name: 암호화
      queue: encrypt_queue

  4:
    - name: 번역
      queue: trans_queue
    - name: 암호화
      queue: encrypt_queue

  5:
    - name: 계산
      queue: calc_queue
    - name: 암호화
      queue: encrypt_queue

  6:
    - name: 계산
      queue: calc_queue
    - name: 번역
      queue: trans_queue
    - name: 암호화
      queue: encrypt_queue  